var EXP = [
    { sid: null, snm: "A", tpid: null },
    { sid: null, snm: "B", tpid: null },
    { sid: null, snm: "C", tpid: null },
    { sid: null, snm: "D", tpid: null },
    { sid: null, snm: "E", tpid: null },
    { sid: null, snm: "F", tpid: null },
    { sid: null, snm: "G", tpid: null },
    { sid: null, snm: "G", tpid: null },
    { sid: null, snm: "I", tpid: null },
    { sid: null, snm: "J", tpid: null },
    { sid: null, snm: "K", tpid: null },
    { sid: null, snm: "L", tpid: null },
    { sid: null, snm: "M", tpid: null },
    { sid: null, snm: "L", tpid: null },
    { sid: null, snm: "O", tpid: null },
    { sid: null, snm: "P", tpid: null },
    { sid: null, snm: "Q", tpid: null },
    { sid: null, snm: "R", tpid: null },
    { sid: null, snm: "S", tpid: null },
    { sid: null, snm: "T", tpid: null },
    { sid: null, snm: "U", tpid: null },
    { sid: null, snm: "V", tpid: null },

]