var CM_COLLECT_SET_DELETE =
{
    "obj": [
        {
            "oid": "0",
            "poid": "-1",
            "onm": "/home/cmuser/mmdl/analyzer/SRC/src/20180129000288/36210",
            "ogid": "/home/cmuser/mmdl/analyzer/SRC/src/20180129000288/36210",
            "otp": "101001",
            "cmoid": ""
        },
        {
            "oid": "1",
            "poid": "0",
            "onm": "36210",
            "ogid": "36210",
            "otp": "101001",
            "cmoid": ""
        },
        {
            "oid": "2",
            "poid": "1",
            "onm": "DYNAMIC_SQL_02",
            "ogid": "DYNAMIC_SQL_02",
            "otp": "101005",
            "cmoid": "36210"
        }
    ],
    "block": [
        {
            "oid": "2",
            "bid": "2",
            "pbid": "-1",
            "btp": "DYNAMIC_SQL_02"
        },
        {
            "oid": "2",
            "bid": "6",
            "pbid": "2",
            "btp": "StatementBlock"
        },
        {
            "oid": "2",
            "bid": "4",
            "pbid": "2",
            "btp": "IF"
        },
        {
            "oid": "2",
            "bid": "5",
            "pbid": "4",
            "btp": "StatementBlock"
        },
        {
            "oid": "2",
            "bid": "3",
            "pbid": "2",
            "btp": "StatementBlock"
        }
    ],
    "node": [
        {
            "bid": "6",
            "nid": "p27",
            "ntp": "STBLOCK_END",
            "sid": null,
            "sln": "39",
            "eln": "39"
        },
        {
            "bid": "6",
            "nid": "p26",
            "ntp": "close",
            "sid": null,
            "sln": "39",
            "eln": "39"
        },
        {
            "bid": "6",
            "nid": "p25",
            "ntp": "etc",
            "sid": null,
            "sln": "37",
            "eln": "37"
        },
        {
            "bid": "6",
            "nid": "p24",
            "ntp": "etc",
            "sid": null,
            "sln": "35",
            "eln": "35"
        },
        {
            "bid": "6",
            "nid": "p23",
            "ntp": "etc",
            "sid": null,
            "sln": "34",
            "eln": "34"
        },
        {
            "bid": "6",
            "nid": "p22",
            "ntp": "etc",
            "sid": null,
            "sln": "31",
            "eln": "31"
        },
        {
            "bid": "6",
            "nid": "p19",
            "ntp": "etc",
            "sid": null,
            "sln": "26",
            "eln": "26"
        },
        {
            "bid": "6",
            "nid": "p21",
            "ntp": "etc",
            "sid": null,
            "sln": "30",
            "eln": "30"
        },
        {
            "bid": "6",
            "nid": "p20",
            "ntp": "etc",
            "sid": null,
            "sln": "27",
            "eln": "27"
        },
        {
            "bid": "6",
            "nid": "p18",
            "ntp": "STBLOCK_START",
            "sid": null,
            "sln": "26",
            "eln": "26"
        },
        {
            "bid": "2",
            "nid": "p28",
            "ntp": "STBLOCK_END",
            "sid": null,
            "sln": "39",
            "eln": "39"
        },
        {
            "bid": "4",
            "nid": "p10start",
            "ntp": "IF_START",
            "sid": null,
            "sln": "20",
            "eln": "20"
        },
        {
            "bid": "4",
            "nid": "p10end",
            "ntp": "IF_END",
            "sid": null,
            "sln": "23",
            "eln": "23"
        },
        {
            "bid": "5",
            "nid": "p15",
            "ntp": "STBLOCK_END",
            "sid": null,
            "sln": "22",
            "eln": "22"
        },
        {
            "bid": "5",
            "nid": "p14",
            "ntp": "etc",
            "sid": null,
            "sln": "22",
            "eln": "22"
        },
        {
            "bid": "5",
            "nid": "p13",
            "ntp": "etc",
            "sid": null,
            "sln": "21",
            "eln": "21"
        },
        {
            "bid": "5",
            "nid": "p12",
            "ntp": "STBLOCK_START",
            "sid": null,
            "sln": "21",
            "eln": "21"
        },
        {
            "bid": "3",
            "nid": "p9",
            "ntp": "fetch",
            "sid": null,
            "sln": "17",
            "eln": "17"
        },
        {
            "bid": "3",
            "nid": "p16",
            "ntp": "STBLOCK_END",
            "sid": null,
            "sln": "17",
            "eln": "17"
        },
        {
            "bid": "3",
            "nid": "p8",
            "ntp": "open",
            "sid": null,
            "sln": "16",
            "eln": "16"
        },
        {
            "bid": "3",
            "nid": "p7",
            "ntp": "Cursor Declaration",
            "sid": null,
            "sln": "9",
            "eln": "12"
        },
        {
            "bid": "3",
            "nid": "p6",
            "ntp": "Variable Declaration",
            "sid": null,
            "sln": "7",
            "eln": "7"
        },
        {
            "bid": "3",
            "nid": "p5",
            "ntp": "Variable Declaration",
            "sid": null,
            "sln": "6",
            "eln": "6"
        },
        {
            "bid": "3",
            "nid": "p4",
            "ntp": "Variable Declaration",
            "sid": null,
            "sln": "5",
            "eln": "5"
        },
        {
            "bid": "3",
            "nid": "p3",
            "ntp": "STBLOCK_START",
            "sid": null,
            "sln": "5",
            "eln": "5"
        },
        {
            "bid": "2",
            "nid": "p1",
            "ntp": "STBLOCK_START",
            "sid": null,
            "sln": "5",
            "eln": "5"
        }
    ],
    "ins": [],
    "edge": [
        {
            "fnid": "p27",
            "tnid": "p28",
            "etp": "direct"
        },
        {
            "fnid": "p26",
            "tnid": "p27",
            "etp": "direct"
        },
        {
            "fnid": "p25",
            "tnid": "p26",
            "etp": "direct"
        },
        {
            "fnid": "p24",
            "tnid": "p25",
            "etp": "direct"
        },
        {
            "fnid": "p23",
            "tnid": "p24",
            "etp": "direct"
        },
        {
            "fnid": "p22",
            "tnid": "p23",
            "etp": "direct"
        },
        {
            "fnid": "p19",
            "tnid": "p20",
            "etp": "direct"
        },
        {
            "fnid": "p21",
            "tnid": "p22",
            "etp": "direct"
        },
        {
            "fnid": "p20",
            "tnid": "p21",
            "etp": "direct"
        },
        {
            "fnid": "p18",
            "tnid": "p19",
            "etp": "direct"
        },
        {
            "fnid": "p10start",
            "tnid": "p10end",
            "etp": "direct"
        },
        {
            "fnid": "p10start",
            "tnid": "p12",
            "etp": "direct"
        },
        {
            "fnid": "p10end",
            "tnid": "p18",
            "etp": "direct"
        },
        {
            "fnid": "p15",
            "tnid": "p10end",
            "etp": "direct"
        },
        {
            "fnid": "p14",
            "tnid": "p15",
            "etp": "direct"
        },
        {
            "fnid": "p13",
            "tnid": "p14",
            "etp": "direct"
        },
        {
            "fnid": "p12",
            "tnid": "p13",
            "etp": "direct"
        },
        {
            "fnid": "p9",
            "tnid": "p16",
            "etp": "direct"
        },
        {
            "fnid": "p16",
            "tnid": "p10start",
            "etp": "direct"
        },
        {
            "fnid": "p8",
            "tnid": "p9",
            "etp": "direct"
        },
        {
            "fnid": "p7",
            "tnid": "p8",
            "etp": "direct"
        },
        {
            "fnid": "p6",
            "tnid": "p7",
            "etp": "direct"
        },
        {
            "fnid": "p5",
            "tnid": "p6",
            "etp": "direct"
        },
        {
            "fnid": "p4",
            "tnid": "p5",
            "etp": "direct"
        },
        {
            "fnid": "p3",
            "tnid": "p4",
            "etp": "direct"
        },
        {
            "fnid": "p1",
            "tnid": "p3",
            "etp": "direct"
        }
    ],
    "src": [],
    "text": [
        {
            "nid": "/home/cmuser/mmdl/analyzer/SRC/src/20180129000288/36210",
            "txt": "36210"
        },
        {
            "nid": "p26",
            "txt": "CLOSE cur_exists;"
        },
        {
            "nid": "p25",
            "txt": "DBMS_OUTPUT . PUT_LINE ( ' ??? ? : ' || v_table_name || '  ??? ? : ' || v_cnt );"
        },
        {
            "nid": "p24",
            "txt": "EXECUTE IMMEDIATE v_str USING v_table_name;"
        },
        {
            "nid": "p23",
            "txt": "v_str := 'INSERT INTO table_rows  VALUES (' || v_cnt || ', :A1 )';"
        },
        {
            "nid": "p22",
            "txt": "EXECUTE IMMEDIATE v_str INTO v_cnt;"
        },
        {
            "nid": "p19",
            "txt": "v_str := 'CREATE  TABLE  table_rows (total number, table_name varchar2(50))';"
        },
        {
            "nid": "p21",
            "txt": "v_str := 'SELECT COUNT(*) cnt FROM ' || v_table_name;"
        },
        {
            "nid": "p20",
            "txt": "EXECUTE IMMEDIATE v_str;"
        },
        {
            "nid": "p10start",
            "txt": "cur_exists % FOUND "
        },
        {
            "nid": "p14",
            "txt": "EXECUTE IMMEDIATE v_str;"
        },
        {
            "nid": "p13",
            "txt": "v_str := 'DROP TABLE  table_rows';"
        },
        {
            "nid": "p12",
            "txt": "THEN"
        },
        {
            "nid": "p9",
            "txt": "FETCH cur_exists INTO v_temp;"
        },
        {
            "nid": "p8",
            "txt": "OPEN cur_exists;"
        },
        {
            "nid": "p7",
            "txt": "CURSOR cur_exists IS SELECT TABLE_NAME FROM USER_TABLES WHERE table_name = 'TABLE_ROWS' ;"
        },
        {
            "nid": "p6",
            "txt": "v_temp VARCHAR2 ( 50 ) ;"
        },
        {
            "nid": "p5",
            "txt": "v_cnt NUMBER ;"
        },
        {
            "nid": "p4",
            "txt": "v_str VARCHAR2 ( 200 ) ;"
        }
    ]
}
